# Site settings
title: "Dog Talk"
description: "Dog Talk is a show by dogs."

language: "en-us"
copyright: "Copyright © 2015 Dog Talk. All rights reserved."
managing_editor:
  name: "Bailey Kalafarski"
  email: "dogtalk@bailey.farski.com"
web_master:
  name: "Bailey Kalafarski"
  email: "dogtalk@bailey.farski.com"

itunes:
  author: "Bailey Kalafarski"
  explicit: "no"
  owner:
    email: "dogtalk@bailey.farski.com"
    name: Bailey Kalafarski
  subtitle: "This is Dog Talk."
  summary: "Dog Talk is a show by dogs."
  category:
  image:
    href: "http://mygreatpodcast.fm/itunes-logo.png"
  keywords:
    - "dog"
    - "animals"
    - "science"

collections:
  - episodes

defaults:
  -
    scope:
      path: ""
      type: "episodes" # a collection in your site, in plural form
    values:
      author: "Bailey Kalafarski"
      itunes:
        author: "Bailey Kalafarski"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dogtalk.bailey.farski.com" # the base hostname & protocol for your site
twitter_username: baileythebeagle

# Build settings
markdown: kramdown

exclude: ['vendor', 'CNAME', 'Gemfile', 'Gemfile.lock']
