# Site settings
title: "Dog Talk"
description: "Dog Talk is a show by dogs."

language: "en-us"
copyright: "Copyright © 2015 Dog Talk. All rights reserved."
managing_editor:
  name: "Bailey Kalafarski"
  email: "dogtalk@bailey.dog"
web_master:
  name: "Bailey Kalafarski"
  email: "dogtalk@bailey.dog"

itunes:
  author: "Bailey Kalafarski"
  explicit: "no"
  owner:
    email: "dogtalk@bailey.dog"
    name: Bailey Kalafarski
  subtitle: "This is Dog Talk."
  summary: "Dog Talk is a show by dogs."
  category:
  image:
    href: "https://s3.amazonaws.com/media-dogtalk.bailey.dog/images/iTunes/3000.png"
  keywords:
    - "dog"
    - "animals"
    - "baileythebeagle"

collections:
  - episodes

defaults:
  -
    scope:
      path: ""
      type: "episodes" # a collection in your site, in plural form
    values:
      author: "dogtalk@bailey.dog (Bailey Kalafarski)"
      link: "http://dogtalk.bailey.dog/"
      source:
        url: "http://dogtalk.bailey.dog/feed.xml"
        text: "Dog Talk"
      itunes:
        author: "Bailey Kalafarski"

url: "http://dogtalk.bailey.dog" # the base hostname & protocol for your site
feed_url: "http://dogtalk.bailey.dog/feed.xml"

# Build settings
markdown: kramdown

exclude: ['vendor', 'CNAME', 'Gemfile', 'Gemfile.lock']
